# Generated by Django 4.1.3 on 2022-12-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuegos',
            name='fecha_lanzamiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='videojuegos',
            name='puntuacion',
            field=models.CharField(max_length=2),
        ),
    ]
