# Generated by Django 4.1.3 on 2022-12-07 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segundaApp', '0002_empleados_id_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='id_empleado',
        ),
    ]
