# Generated by Django 4.1.3 on 2022-12-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segundaApp', '0003_remove_empleados_id_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
