# Generated by Django 4.1.3 on 2022-12-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segundaApp', '0004_alter_empleados_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='horario',
            field=models.CharField(max_length=50),
        ),
    ]
