# Generated by Django 4.1.3 on 2022-12-07 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('segundaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Portatil', 'Portatil'), ('Fijo', 'Fijo')], max_length=8, null=True)),
                ('marca', models.CharField(max_length=50)),
                ('capacidad', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=6)),
                ('garantia', models.CharField(max_length=50)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segundaApp.empleados')),
            ],
        ),
    ]
